import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Language = "en" | "hi" | "ta" | "te" | "bn" | "mr";

export const LANGUAGES: { code: Language; name: string; nativeName: string; flag: string }[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
];

export const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    reportIssue: "Report Issue",
    dashboard: "Dashboard",
    leaderboard: "Leaderboard",
    wallet: "Wallet",
    contact: "Contact",
    login: "Login",
    logout: "Logout",
    authority: "Authority",
    register: "Register",
    heroTitle: "Let's Clean Our Society",
    heroSubtitle: "Report civic issues with a photo. Our AI instantly identifies the problem, routes it to the right authority, and rewards you for making India cleaner.",
    reportAnIssue: "Report an Issue",
    viewDashboard: "View Dashboard",
    platformImpact: "Platform Impact",
    totalIssues: "Total Issues",
    resolved: "Resolved",
    inProgress: "In Progress",
    pending: "Pending",
    recentReports: "Recent Reports",
    uploadPhoto: "Upload Photo",
    location: "Location",
    description: "Description",
    submit: "Submit Report",
    aiDetecting: "AI Detecting...",
    issueDetected: "Issue Detected",
    routedTo: "Routed to",
    welcomeBack: "Welcome Back",
    signIn: "Sign in to your CivicAI account",
    createAccount: "Create Account",
    joinCivicAI: "Join CivicAI and earn rewards",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    phone: "Phone (optional)",
    signInBtn: "Sign In",
    createAccountBtn: "Create Account",
    tryDemo: "Try Demo Account",
    newToCivicAI: "New to CivicAI?",
    alreadyHaveAccount: "Already have an account?",
    authorityLogin: "Authority Login",
    authoritySubtitle: "For municipal and department officials",
    loginAsAuthority: "Login as Authority",
    demoAccounts: "Demo Accounts",
    authorityPanel: "Authority Panel",
    totalAssigned: "Total Assigned",
    acceptAndStart: "Accept & Start",
    markResolved: "Mark Resolved",
    noIssues: "No issues assigned yet.",
    topContributors: "Top Contributors",
    pointsBalance: "Points Balance",
    cashValue: "Cash Value",
    withdraw: "Withdraw",
    transactionHistory: "Transaction History",
    contactUs: "Contact Us",
    sendMessage: "Send Message",
    name: "Name",
    subject: "Subject",
    message: "Message",
    invalidCredentials: "Invalid email or password.",
    emailExists: "Email already registered.",
    registrationFailed: "Registration failed. Please try again.",
    reports: "reports",
    resolvedLabel: "resolved",
    autoDetectGPS: "Auto-detect GPS",
    addressLandmark: "Address / Landmark",
    describeIssue: "Describe the issue (optional)",
    clickToUpload: "Click to upload or drag & drop",
    fileTypes: "JPG, PNG, HEIC up to 10MB",
    submitting: "Submitting...",
    filter: "Filter",
    allStatus: "All Status",
    allTypes: "All Types",
    reportedBy: "Reported by",
    points: "points",
  },
  hi: {
    home: "होम",
    reportIssue: "समस्या रिपोर्ट करें",
    dashboard: "डैशबोर्ड",
    leaderboard: "लीडरबोर्ड",
    wallet: "वॉलेट",
    contact: "संपर्क",
    login: "लॉगिन",
    logout: "लॉगआउट",
    authority: "अधिकारी",
    register: "रजिस्टर",
    heroTitle: "आइए अपना समाज साफ करें",
    heroSubtitle: "फोटो के साथ नागरिक समस्याएं रिपोर्ट करें। हमारा AI तुरंत समस्या की पहचान करता है, सही विभाग को भेजता है, और आपको पुरस्कृत करता है।",
    reportAnIssue: "समस्या रिपोर्ट करें",
    viewDashboard: "डैशबोर्ड देखें",
    platformImpact: "प्लेटफॉर्म का प्रभाव",
    totalIssues: "कुल समस्याएं",
    resolved: "हल की गईं",
    inProgress: "प्रगति में",
    pending: "लंबित",
    recentReports: "हाल की रिपोर्ट",
    uploadPhoto: "फोटो अपलोड करें",
    location: "स्थान",
    description: "विवरण",
    submit: "रिपोर्ट सबमिट करें",
    aiDetecting: "AI पहचान कर रहा है...",
    issueDetected: "समस्या पहचानी गई",
    routedTo: "भेजा गया",
    welcomeBack: "वापस स्वागत है",
    signIn: "अपने CivicAI खाते में साइन इन करें",
    createAccount: "खाता बनाएं",
    joinCivicAI: "CivicAI से जुड़ें और पुरस्कार कमाएं",
    email: "ईमेल",
    password: "पासवर्ड",
    fullName: "पूरा नाम",
    phone: "फोन (वैकल्पिक)",
    signInBtn: "साइन इन करें",
    createAccountBtn: "खाता बनाएं",
    tryDemo: "डेमो खाता आज़माएं",
    newToCivicAI: "CivicAI में नए हैं?",
    alreadyHaveAccount: "पहले से खाता है?",
    authorityLogin: "अधिकारी लॉगिन",
    authoritySubtitle: "नगर पालिका और विभाग अधिकारियों के लिए",
    loginAsAuthority: "अधिकारी के रूप में लॉगिन करें",
    demoAccounts: "डेमो खाते",
    authorityPanel: "अधिकारी पैनल",
    totalAssigned: "कुल सौंपी गई",
    acceptAndStart: "स्वीकार करें और शुरू करें",
    markResolved: "हल के रूप में चिह्नित करें",
    noIssues: "अभी तक कोई समस्या नहीं सौंपी गई।",
    topContributors: "शीर्ष योगदानकर्ता",
    pointsBalance: "पॉइंट्स बैलेंस",
    cashValue: "नकद मूल्य",
    withdraw: "निकालें",
    transactionHistory: "लेन-देन इतिहास",
    contactUs: "हमसे संपर्क करें",
    sendMessage: "संदेश भेजें",
    name: "नाम",
    subject: "विषय",
    message: "संदेश",
    invalidCredentials: "अमान्य ईमेल या पासवर्ड।",
    emailExists: "ईमेल पहले से पंजीकृत है।",
    registrationFailed: "पंजीकरण विफल। कृपया पुनः प्रयास करें।",
    reports: "रिपोर्ट",
    resolvedLabel: "हल की गई",
    autoDetectGPS: "GPS से स्थान प्राप्त करें",
    addressLandmark: "पता / लैंडमार्क",
    describeIssue: "समस्या का विवरण दें (वैकल्पिक)",
    clickToUpload: "अपलोड करने के लिए क्लिक करें",
    fileTypes: "JPG, PNG, HEIC अधिकतम 10MB",
    submitting: "सबमिट हो रहा है...",
    filter: "फ़िल्टर",
    allStatus: "सभी स्थिति",
    allTypes: "सभी प्रकार",
    reportedBy: "द्वारा रिपोर्ट किया गया",
    points: "पॉइंट्स",
  },
  ta: {
    home: "முகப்பு",
    reportIssue: "பிரச்சினை புகாரளிக்க",
    dashboard: "டாஷ்போர்டு",
    leaderboard: "லீடர்போர்டு",
    wallet: "வாலட்",
    contact: "தொடர்பு",
    login: "உள்நுழைய",
    logout: "வெளியேறு",
    authority: "அதிகாரம்",
    register: "பதிவு செய்",
    heroTitle: "நம் சமூகத்தை சுத்தப்படுத்துவோம்",
    heroSubtitle: "புகைப்படத்துடன் குடிமைப் பிரச்சினைகளை புகாரளிக்கவும். எங்கள் AI உடனடியாக சிக்கலை கண்டறிந்து சரியான அதிகாரிக்கு அனுப்புகிறது.",
    reportAnIssue: "பிரச்சினை புகாரளிக்க",
    viewDashboard: "டாஷ்போர்டு காண்க",
    platformImpact: "தளத்தின் தாக்கம்",
    totalIssues: "மொத்த பிரச்சினைகள்",
    resolved: "தீர்க்கப்பட்டவை",
    inProgress: "நடந்து வருகின்றன",
    pending: "நிலுவையில் உள்ளவை",
    recentReports: "சமீபத்திய அறிக்கைகள்",
    uploadPhoto: "புகைப்படம் பதிவேற்றவும்",
    location: "இடம்",
    description: "விளக்கம்",
    submit: "அறிக்கை சமர்ப்பிக்கவும்",
    aiDetecting: "AI கண்டறிகிறது...",
    issueDetected: "பிரச்சினை கண்டறியப்பட்டது",
    routedTo: "அனுப்பப்பட்டது",
    welcomeBack: "மீண்டும் வருக",
    signIn: "உங்கள் CivicAI கணக்கில் உள்நுழையவும்",
    createAccount: "கணக்கு உருவாக்கவும்",
    joinCivicAI: "CivicAI-ல் சேர்ந்து பரிசுகள் பெறுங்கள்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    fullName: "முழு பெயர்",
    phone: "தொலைபேசி (விருப்பமானது)",
    signInBtn: "உள்நுழைக",
    createAccountBtn: "கணக்கு உருவாக்கவும்",
    tryDemo: "டெமோ கணக்கை முயற்சிக்கவும்",
    newToCivicAI: "CivicAI-ல் புதியவரா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு இருக்கிறதா?",
    authorityLogin: "அதிகாரி உள்நுழைவு",
    authoritySubtitle: "நகர சபை மற்றும் துறை அதிகாரிகளுக்கு",
    loginAsAuthority: "அதிகாரியாக உள்நுழைக",
    demoAccounts: "டெமோ கணக்குகள்",
    authorityPanel: "அதிகாரி பலகை",
    totalAssigned: "மொத்த ஒதுக்கப்பட்டவை",
    acceptAndStart: "ஏற்று தொடங்கு",
    markResolved: "தீர்க்கப்பட்டதாக குறி",
    noIssues: "இன்னும் பிரச்சினைகள் ஒதுக்கப்படவில்லை.",
    topContributors: "சிறந்த பங்களிப்பாளர்கள்",
    pointsBalance: "புள்ளிகள் இருப்பு",
    cashValue: "பண மதிப்பு",
    withdraw: "எடு",
    transactionHistory: "பரிவர்த்தனை வரலாறு",
    contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்",
    sendMessage: "செய்தி அனுப்பு",
    name: "பெயர்",
    subject: "பொருள்",
    message: "செய்தி",
    invalidCredentials: "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.",
    emailExists: "மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.",
    registrationFailed: "பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
    reports: "அறிக்கைகள்",
    resolvedLabel: "தீர்க்கப்பட்டது",
    autoDetectGPS: "GPS மூலம் இடம் கண்டறி",
    addressLandmark: "முகவரி / அடையாளம்",
    describeIssue: "பிரச்சினையை விவரிக்கவும் (விருப்பமானது)",
    clickToUpload: "பதிவேற்ற கிளிக் செய்யவும்",
    fileTypes: "JPG, PNG, HEIC அதிகபட்சம் 10MB",
    submitting: "சமர்ப்பிக்கிறது...",
    filter: "வடிகட்டு",
    allStatus: "அனைத்து நிலைகள்",
    allTypes: "அனைத்து வகைகள்",
    reportedBy: "புகாரளித்தவர்",
    points: "புள்ளிகள்",
  },
  te: {
    home: "హోమ్",
    reportIssue: "సమస్య నివేదించు",
    dashboard: "డాష్‌బోర్డ్",
    leaderboard: "లీడర్‌బోర్డ్",
    wallet: "వాలెట్",
    contact: "సంప్రదించు",
    login: "లాగిన్",
    logout: "లాగ్అవుట్",
    authority: "అధికారి",
    register: "నమోదు చేయి",
    heroTitle: "మన సమాజాన్ని శుభ్రం చేద్దాం",
    heroSubtitle: "ఫోటోతో పౌర సమస్యలు నివేదించండి. మా AI వెంటనే సమస్యను గుర్తించి సరైన అధికారికి పంపుతుంది.",
    reportAnIssue: "సమస్య నివేదించు",
    viewDashboard: "డాష్‌బోర్డ్ చూడు",
    platformImpact: "వేదిక ప్రభావం",
    totalIssues: "మొత్తం సమస్యలు",
    resolved: "పరిష్కరించబడినవి",
    inProgress: "పురోగతిలో ఉన్నవి",
    pending: "పెండింగ్",
    recentReports: "ఇటీవలి నివేదికలు",
    uploadPhoto: "ఫోటో అప్‌లోడ్ చేయి",
    location: "స్థానం",
    description: "వివరణ",
    submit: "నివేదిక సమర్పించు",
    aiDetecting: "AI గుర్తిస్తోంది...",
    issueDetected: "సమస్య గుర్తించబడింది",
    routedTo: "పంపబడింది",
    welcomeBack: "తిరిగి స్వాగతం",
    signIn: "మీ CivicAI ఖాతాలో సైన్ ఇన్ చేయండి",
    createAccount: "ఖాతా సృష్టించు",
    joinCivicAI: "CivicAI లో చేరి బహుమతులు సంపాదించండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    fullName: "పూర్తి పేరు",
    phone: "ఫోన్ (ఐచ్ఛికం)",
    signInBtn: "సైన్ ఇన్",
    createAccountBtn: "ఖాతా సృష్టించు",
    tryDemo: "డెమో ఖాతా ప్రయత్నించు",
    newToCivicAI: "CivicAI లో కొత్తవారా?",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    authorityLogin: "అధికారి లాగిన్",
    authoritySubtitle: "మున్సిపాలిటీ మరియు విభాగ అధికారుల కోసం",
    loginAsAuthority: "అధికారిగా లాగిన్ చేయి",
    demoAccounts: "డెమో ఖాతాలు",
    authorityPanel: "అధికారి ప్యానెల్",
    totalAssigned: "మొత్తం కేటాయించబడినవి",
    acceptAndStart: "అంగీకరించి ప్రారంభించు",
    markResolved: "పరిష్కరించబడినదిగా గుర్తించు",
    noIssues: "ఇంకా సమస్యలు కేటాయించబడలేదు.",
    topContributors: "అగ్ర సహకారులు",
    pointsBalance: "పాయింట్ల బ్యాలెన్స్",
    cashValue: "నగదు విలువ",
    withdraw: "ఉపసంహరించు",
    transactionHistory: "లావాదేవీ చరిత్ర",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    sendMessage: "సందేశం పంపు",
    name: "పేరు",
    subject: "విషయం",
    message: "సందేశం",
    invalidCredentials: "తప్పు ఇమెయిల్ లేదా పాస్‌వర్డ్.",
    emailExists: "ఇమెయిల్ ఇప్పటికే నమోదు చేయబడింది.",
    registrationFailed: "నమోదు విఫలమైంది. మళ్ళీ ప్రయత్నించండి.",
    reports: "నివేదికలు",
    resolvedLabel: "పరిష్కరించబడింది",
    autoDetectGPS: "GPS ద్వారా స్థానం గుర్తించు",
    addressLandmark: "చిరునామా / లాండ్‌మార్క్",
    describeIssue: "సమస్య వివరించండి (ఐచ్ఛికం)",
    clickToUpload: "అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
    fileTypes: "JPG, PNG, HEIC గరిష్టంగా 10MB",
    submitting: "సమర్పిస్తోంది...",
    filter: "వడపోత",
    allStatus: "అన్ని స్థితులు",
    allTypes: "అన్ని రకాలు",
    reportedBy: "నివేదించినవారు",
    points: "పాయింట్లు",
  },
  bn: {
    home: "হোম",
    reportIssue: "সমস্যা রিপোর্ট করুন",
    dashboard: "ড্যাশবোর্ড",
    leaderboard: "লিডারবোর্ড",
    wallet: "ওয়ালেট",
    contact: "যোগাযোগ",
    login: "লগইন",
    logout: "লগআউট",
    authority: "কর্তৃপক্ষ",
    register: "নিবন্ধন",
    heroTitle: "আসুন আমাদের সমাজ পরিষ্কার করি",
    heroSubtitle: "ছবি দিয়ে নাগরিক সমস্যা রিপোর্ট করুন। আমাদের AI তাৎক্ষণিকভাবে সমস্যা চিহ্নিত করে সঠিক কর্তৃপক্ষের কাছে পাঠায়।",
    reportAnIssue: "সমস্যা রিপোর্ট করুন",
    viewDashboard: "ড্যাশবোর্ড দেখুন",
    platformImpact: "প্ল্যাটফর্মের প্রভাব",
    totalIssues: "মোট সমস্যা",
    resolved: "সমাধান হয়েছে",
    inProgress: "চলমান",
    pending: "মুলতুবি",
    recentReports: "সাম্প্রতিক রিপোর্ট",
    uploadPhoto: "ছবি আপলোড করুন",
    location: "অবস্থান",
    description: "বিবরণ",
    submit: "রিপোর্ট জমা দিন",
    aiDetecting: "AI সনাক্ত করছে...",
    issueDetected: "সমস্যা সনাক্ত হয়েছে",
    routedTo: "পাঠানো হয়েছে",
    welcomeBack: "ফিরে আসুন",
    signIn: "আপনার CivicAI অ্যাকাউন্টে সাইন ইন করুন",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    joinCivicAI: "CivicAI-এ যোগ দিন এবং পুরস্কার অর্জন করুন",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    fullName: "পুরো নাম",
    phone: "ফোন (ঐচ্ছিক)",
    signInBtn: "সাইন ইন করুন",
    createAccountBtn: "অ্যাকাউন্ট তৈরি করুন",
    tryDemo: "ডেমো অ্যাকাউন্ট চেষ্টা করুন",
    newToCivicAI: "CivicAI-এ নতুন?",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    authorityLogin: "কর্তৃপক্ষের লগইন",
    authoritySubtitle: "পৌরসভা এবং বিভাগীয় কর্মকর্তাদের জন্য",
    loginAsAuthority: "কর্তৃপক্ষ হিসেবে লগইন করুন",
    demoAccounts: "ডেমো অ্যাকাউন্ট",
    authorityPanel: "কর্তৃপক্ষের প্যানেল",
    totalAssigned: "মোট নির্ধারিত",
    acceptAndStart: "গ্রহণ করুন এবং শুরু করুন",
    markResolved: "সমাধান হিসেবে চিহ্নিত করুন",
    noIssues: "এখনো কোনো সমস্যা নির্ধারিত হয়নি।",
    topContributors: "শীর্ষ অবদানকারী",
    pointsBalance: "পয়েন্ট ব্যালেন্স",
    cashValue: "নগদ মূল্য",
    withdraw: "উত্তোলন",
    transactionHistory: "লেনদেনের ইতিহাস",
    contactUs: "আমাদের সাথে যোগাযোগ করুন",
    sendMessage: "বার্তা পাঠান",
    name: "নাম",
    subject: "বিষয়",
    message: "বার্তা",
    invalidCredentials: "ভুল ইমেইল বা পাসওয়ার্ড।",
    emailExists: "ইমেইল ইতিমধ্যে নিবন্ধিত।",
    registrationFailed: "নিবন্ধন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    reports: "রিপোর্ট",
    resolvedLabel: "সমাধান হয়েছে",
    autoDetectGPS: "GPS দিয়ে অবস্থান সনাক্ত করুন",
    addressLandmark: "ঠিকানা / ল্যান্ডমার্ক",
    describeIssue: "সমস্যা বর্ণনা করুন (ঐচ্ছিক)",
    clickToUpload: "আপলোড করতে ক্লিক করুন",
    fileTypes: "JPG, PNG, HEIC সর্বোচ্চ 10MB",
    submitting: "জমা দেওয়া হচ্ছে...",
    filter: "ফিল্টার",
    allStatus: "সব স্ট্যাটাস",
    allTypes: "সব ধরন",
    reportedBy: "রিপোর্ট করেছেন",
    points: "পয়েন্ট",
  },
  mr: {
    home: "मुखपृष्ठ",
    reportIssue: "समस्या नोंदवा",
    dashboard: "डॅशबोर्ड",
    leaderboard: "लीडरबोर्ड",
    wallet: "वॉलेट",
    contact: "संपर्क",
    login: "लॉगिन",
    logout: "लॉगआउट",
    authority: "प्राधिकरण",
    register: "नोंदणी",
    heroTitle: "चला आपला समाज स्वच्छ करूया",
    heroSubtitle: "फोटोसह नागरी समस्या नोंदवा. आमचे AI त्वरित समस्या ओळखते, योग्य विभागाला पाठवते आणि तुम्हाला बक्षीस देते.",
    reportAnIssue: "समस्या नोंदवा",
    viewDashboard: "डॅशबोर्ड पहा",
    platformImpact: "प्लॅटफॉर्मचा प्रभाव",
    totalIssues: "एकूण समस्या",
    resolved: "सोडवलेल्या",
    inProgress: "प्रगतीत",
    pending: "प्रलंबित",
    recentReports: "अलीकडील अहवाल",
    uploadPhoto: "फोटो अपलोड करा",
    location: "स्थान",
    description: "वर्णन",
    submit: "अहवाल सादर करा",
    aiDetecting: "AI ओळखत आहे...",
    issueDetected: "समस्या ओळखली",
    routedTo: "पाठवले",
    welcomeBack: "पुन्हा स्वागत",
    signIn: "तुमच्या CivicAI खात्यात साइन इन करा",
    createAccount: "खाते तयार करा",
    joinCivicAI: "CivicAI मध्ये सामील व्हा आणि बक्षिसे मिळवा",
    email: "ईमेल",
    password: "पासवर्ड",
    fullName: "पूर्ण नाव",
    phone: "फोन (पर्यायी)",
    signInBtn: "साइन इन करा",
    createAccountBtn: "खाते तयार करा",
    tryDemo: "डेमो खाते वापरून पहा",
    newToCivicAI: "CivicAI मध्ये नवीन आहात?",
    alreadyHaveAccount: "आधीच खाते आहे?",
    authorityLogin: "प्राधिकरण लॉगिन",
    authoritySubtitle: "नगरपालिका आणि विभाग अधिकाऱ्यांसाठी",
    loginAsAuthority: "प्राधिकरण म्हणून लॉगिन करा",
    demoAccounts: "डेमो खाती",
    authorityPanel: "प्राधिकरण पॅनेल",
    totalAssigned: "एकूण नियुक्त",
    acceptAndStart: "स्वीकारा आणि सुरू करा",
    markResolved: "सोडवले म्हणून चिन्हांकित करा",
    noIssues: "अद्याप कोणत्याही समस्या नियुक्त केल्या नाहीत.",
    topContributors: "शीर्ष योगदानकर्ते",
    pointsBalance: "गुण शिल्लक",
    cashValue: "रोख मूल्य",
    withdraw: "काढा",
    transactionHistory: "व्यवहार इतिहास",
    contactUs: "आमच्याशी संपर्क साधा",
    sendMessage: "संदेश पाठवा",
    name: "नाव",
    subject: "विषय",
    message: "संदेश",
    invalidCredentials: "चुकीचा ईमेल किंवा पासवर्ड.",
    emailExists: "ईमेल आधीच नोंदणीकृत आहे.",
    registrationFailed: "नोंदणी अयशस्वी. पुन्हा प्रयत्न करा.",
    reports: "अहवाल",
    resolvedLabel: "सोडवले",
    autoDetectGPS: "GPS द्वारे स्थान शोधा",
    addressLandmark: "पत्ता / खूण",
    describeIssue: "समस्या वर्णन करा (पर्यायी)",
    clickToUpload: "अपलोड करण्यासाठी क्लिक करा",
    fileTypes: "JPG, PNG, HEIC जास्तीत जास्त 10MB",
    submitting: "सादर होत आहे...",
    filter: "फिल्टर",
    allStatus: "सर्व स्थिती",
    allTypes: "सर्व प्रकार",
    reportedBy: "नोंदवले",
    points: "गुण",
  },
};

type LanguageContextType = {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem("civicai_lang");
      if (saved && saved in translations) return saved as Language;
    } catch {}
    return "en";
  });

  const setLang = (l: Language) => {
    setLangState(l);
    try { localStorage.setItem("civicai_lang", l); } catch {}
  };

  const t = (key: string): string =>
    translations[lang]?.[key] ?? translations["en"]?.[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
