import { createRoot } from "react-dom/client";
import { setAuthTokenGetter } from "@workspace/api-client-react";
import App from "./App";
import "./index.css";

// Attach JWT to all `/api/*` requests generated by Orval.
setAuthTokenGetter(() => localStorage.getItem("civicai_token"));

createRoot(document.getElementById("root")!).render(<App />);
